version: '3.8'

services:
  umbraco:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: umbraco_container
    ports:
      - "8080:80"  # Map port 80 in the container to port 8080 on the host
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost/ || exit 1"]
      interval: 5m
      timeout: 3s
      retries: 3
      start_period: 2m
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

# Optional volumes for persistence, add as needed
# volumes:
#   - ./data:/app/data
