version: "3.2"
services:
  admin:
    container_name: umbraco_admin
    hostname: umbraco_admin
    image: umbraco
    ports:
      - "8000:8000"
    networks:
      - webnet
    environment:
      Umbraco_IsMaster: "true"
      Umbraco_ApplicationUrl: "umbraco-admin"

networks:
  webnet:

volumes:
  umbraco_data:
    external: true
