version: '3.8'

services:
  umbraco:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: umbraco_container
    ports:
      - "8081:80"  # Change the host port to 8081
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost/ || exit 1"]
      interval: 5m
      timeout: 3s
      retries: 3
      start_period: 2m
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

# Optional volumes for persistence, add as needed
# volumes:
#   - ./data:/app/data
